export const APP_URL = process.env.NEXT_PUBLIC_APP_URL!

export const APPWRITE_ENDPOINT = process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT!

export const APPWRITE_PROJECT = process.env.NEXT_PUBLIC_APPWRITE_PROJECT!

export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE!

export const WORKSPACES_ID = process.env.NEXT_PUBLIC_APPWRITE_WORKSPACES!

export const MEMBERS_ID = process.env.NEXT_PUBLIC_APPWRITE_MEMBERS!
export const PROJECTS_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJECTS!
export const TASKS_ID = process.env.NEXT_PUBLIC_APPWRITE_TASKS!


export const IMAGES_BUCKET_ID = process.env.NEXT_PUBLIC_APPWRITE_IMAGES_BUCKET!
