import "./globals.css"
import "@/features/tasks/components/data-calendar.css"

import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { NuqsAdapter } from "nuqs/adapters/next/app"

import { QueryProvider } from "@/components/query-provider"
import { Toaster } from "@/components/ui/sonner"
import { cn } from "@/lib/utils"

const inter = Inter({
   variable: "--font-inter",
   subsets: ["latin"]
})

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app"
}

export default function RootLayout({
   children
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html lang="en">
         <body className={cn(inter.className, "min-h-screen antialiased")}>
            <QueryProvider>
               <NuqsAdapter>
                  <Toaster />
                  {children}
               </NuqsAdapter>
            </QueryProvider>
         </body>
      </html>
   )
}
